FROM node:22-alpine

RUN apk update
RUN apk add --no-cache libc6-compat

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

RUN corepack enable pnpm \ 
    && corepack prepare pnpm@latest --activate \
    && pnpm --version

# Set working directory
WORKDIR /app

RUN pnpm add -g turbo@2.5.6

COPY . .

RUN turbo prune @acme/next --docker

RUN pnpm install --frozen-lockfile

CMD ["pnpm", "db:deploy"]