import "~/styles/globals.css";

import { type Metadata } from "next";
import { Vazirmatn } from "next/font/google";

import { TRPCProvider } from "~/utils/trpc";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const vazirmatn = Vazirmatn({
  subsets: ["arabic", "latin"],
  variable: "--font-vazir",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="fa" className={`${vazirmatn.variable}`}>
      <body dir="rtl" className="font-sans">
        <TRPCProvider>{children}</TRPCProvider>
      </body>
    </html>
  );
}
